name: Build MEGA APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout repo
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Step 3: Install Capacitor CLI (in case not in repo)
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli || echo "Already installed"

    # Step 4: Install dependencies if package.json exists
    - name: Install dependencies
      run: npm install || echo "No package.json found, skipping npm install"

    # Step 5: Sync Capacitor
    - name: Sync Capacitor
      run: npx cap sync android

    # Step 6: Build APK
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    # Step 7: Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MEGA-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
