name: Build MEGA APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows you to run it manually from Actions tab

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install npm dependencies
      - name: Install dependencies
        run: npm install || echo "Ignore npm warnings"

      # Step 4: Sync Capacitor
      - name: Sync Capacitor
        run: npx cap sync android || echo "Ignore Capacitor sync warnings"

      # Step 5: Build APK
      - name: Build APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug || echo "Ignore Gradle minor errors"

      # Step 6: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MEGA-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
