name: Build MEGA APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout repo
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        cd MEGA  # replace with your project folder if different
        npm install

    # Step 4: Sync Capacitor
    - name: Sync Capacitor
      run: |
        cd MEGA
        npx cap sync android

    # Step 5: Build APK
    - name: Build APK
      run: |
        cd MEGA/android
        ./gradlew assembleDebug

    # Step 6: Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MEGA-debug.apk
        path: MEGA/android/app/build/outputs/apk/debug/app-debug.apk
